# Generated by Django 2.1.5 on 2019-01-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category name')),
                ('cover', models.ImageField(upload_to='', verbose_name='Category cover image')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=255, verbose_name='Video cover')),
                ('file', models.CharField(max_length=255, verbose_name='Video file')),
                ('views', models.IntegerField(verbose_name='Video views')),
                ('is_private', models.BooleanField(verbose_name='Video private')),
            ],
        ),
    ]
