# Generated by Django 2.1.5 on 2019-01-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Video name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(upload_to='', verbose_name='Video cover image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Video file'),
        ),
    ]
